### ISSUE TITLE
[general] Supernode vs node on NEM

### ISSUE THREAD

**Issue by mcb345** [NemProject/nem#10]
If I dont wanna have 3millions NEM on my account, can I just be a regular NEM node ? I am planning to create an exchange platform , or do I NEED to have those balance in order to be a node ? Is there such node because there is supernode (at least why not just call it a node instead ?)

**Comment by gimre-xymcity** [comment]
also cc @0x6861746366574 as I guess this can be referenced when we re-launch *S* N programme

**Comment by 0x6861746366574** [comment]
I'm not sure we would want to reference it. 😅
